name:                gitload
version:             0.1.0.0
github:              "hugdro/gitload"
license:             BSD3
author:              "Hugo DesRosiers"
maintainer:          "hugo.desrosiers@boardingcities.com"
copyright:           "None."

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            software.

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/hugdro/gitload#readme>

dependencies:
  - aeson
  - base >= 4.7 && < 5
  - bytestring
  - directory
  - text
  - time
  - vector
  # For YAML (config file):
  - yaml
  - directory
  - filepath
  # For Git (version):
  - gitrev
  # For options:
  - optparse-applicative
  - unix
  # For Cont(T):
  - mtl
  # For SQL:
  - postgresql-binary
  - hasql
  - hasql-th
  - hasql-pool
  # For multi-threadedfilesystem exploration:
  - pathwalk
  - containers
  - async
  # For git ops:
  - gitlib
  - gitlib-libgit2
  - tagged

default-extensions:
- OverloadedStrings
- DuplicateRecordFields
- OverloadedRecordDot

ghc-options:
# - -Wall
# - -Wunused-matches
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
#- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  gitload:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - gitload

tests:
  gitload-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - gitload
